version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: ecommercedb
      MYSQL_USER: root
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "3307:3306"
    volumes:
      - ecommercedata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma2
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  ecommercedata: