services:

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USER: ${USER:-appuser}
        GROUP: ${GROUP:-appgroup}
        APP_CODE_PATH_CONTAINER: ${APP_CODE_PATH_CONTAINER}
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: ${APP_CODE_PATH_CONTAINER}
    ports:
      - ${PORT_APP}:9000
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${PORT_DB}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:delegated
      - ./app/config/php.ini:/usr/local/etc/php/php.ini
      - ./app/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./app/config/msmtp.conf:/home/${USER:-appuser}/.msmtprc
      - ./app/start.sh:/start.sh
    command: ["/start.sh"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${PORT_WEB}:80
      - ${PORT_WEB_SSL}:443
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:delegated
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - VIRTUAL_HOST=${VIRTUAL_HOST},www.${VIRTUAL_HOST}
    depends_on:
      - app
  
  db:
    image: mysql:8.0.39
    ports:
      - ${PORT_DB}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - ./db/local/db:/var/lib/mysql
      - ./db/local/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/local/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  redis:
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - /data
