services:
  mail:
    image: schickling/mailcatcher
    ports:
      - ${PORT_MAIL}:1080
    expose:
      - 1025

  system_db:
    image: biarms/mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_SYSTEM_DATABASE}
      - MYSQL_USER=${MYSQL_SYSTEM_USER}
      - MYSQL_PASSWORD=${MYSQL_SYSTEM_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_SYSTEM_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - ./db/system/db:/var/lib/mysql
      - ./db/system/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/system/initdb:/docker-entrypoint-initdb.d

  ssh:
    image: panubo/sshd
    ports:
      - "${PORT_SSH}:22"
    volumes:
      - ./ssh/setpasswd.sh:/etc/entrypoint.d/setpasswd.sh
      - ./ssh/config/authorized_keys:/root/.ssh/authorized_keys
      - ./ssh/log:/var/log
    environment:
      - SSH_ROOT_PASSWORD=${SSH_ROOT_PASSWORD}
      - SSH_ENABLE_ROOT_PASSWORD_AUTH=false
      - GATEWAY_PORTS=true
      - TCP_FORWARDING=true
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PORT_PHPMYADMIN}:80
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - MEMORY_LIMIT=${PHPMYADMIN_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PHPMYADMIN_UPLOAD_LIMIT}
    restart: unless-stopped

