services:
  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
      - ${PORT_PHPMYADMIN}:80
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - MEMORY_LIMIT=${PHPMYADMIN_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PHPMYADMIN_UPLOAD_LIMIT}
    restart: unless-stopped

